### ISSUE TITLE
Multiple Joint State Topics

### ISSUE THREAD

**Issue by n0sc3tipsum** [PickNikRobotics/topic_based_ros2_control#26]
Hi,

I am trying to use this package to read joint states of two of my wheels which are being published by an ESP32 via a Micro-ROS agent. As of now, I have made it so that each wheel state is published to its' own topic. 

So I am a bit unsure of how this would integrate with this package. 

- Should I publish both wheel states as their own messages to a single topic
- Is there a way to have two individual topics where joint states can be published?
- Or is there a message that would contain the joint states of multiple joints?

Thank you!

**Comment by hijimasa** [comment]
The line 151 in topic_based_system.cpp shows this package only saves latest joint state topic.
So I think you should publish a single topic that integrates each wheel state from your ESP32.

The topic that this package publishes contains the joint commands of multiple joints.
The correspondence between joint names and joint commands should be checked.

**Comment by n0sc3tipsum** [comment]
> The line 151 in topic_based_system.cpp shows this package only saves latest joint state topic. So I think you should publish a single topic that integrates each wheel state from your ESP32.
> 
> The topic that this package publishes contains the joint commands of multiple joints. The correspondence between joint names and joint commands should be checked.

Hi, thanks for the response. So you mean I just publish both messages independently or would I have to join them into a single message?

**Comment by hijimasa** [comment]
You should join each wheel states into a single message.

**Comment by n0sc3tipsum** [comment]
Oh okay I see, thank you so much! One last question, would that message be a joint state sequence then?

**Comment by hijimasa** [comment]
What do you mean a joint state sequence?

**Comment by n0sc3tipsum** [comment]
As in, since I'm using micro-ROS, they have a message type for Joint State messages that forms a sequence (vector of joint state messages I feel like)

```

**Comment by hijimasa** [comment]
Sorry, I don't know micro-ROS well.
In default environment, two wheel states integrate a single message like below.
Example:
Left Wheel Message
```
header:
  stamp:
    sec: 1718174785
    nanosec: 886196307
  frame_id: ''
name:
- left_wheel_joint
position:
- 1.0
velocity:
- 2.0
effort:
- 3.0
---
```
Right Wheel Message
```
header:
  stamp:
    sec: 1718174785
    nanosec: 886196307
  frame_id: ''
name:
- right_wheel_joint
position:
- 4.0
velocity:
- 5.0
effort:
- 6.0
---
```
Integrated Message
```
header:
  stamp:
    sec: 1718174785
    nanosec: 886196307
  frame_id: ''
name:
- left_wheel_joint
- right_wheel_joint
position:
- 1.0
- 4.0
velocity:
- 2.0
- 5.0
effort:
- 3.0
- 6.0
---
```
